### ISSUE TITLE
[Phase 1] Dockerベース開発環境の構築

### ISSUE THREAD

**Issue by umaidashi** [umaidashi/open-notebooklm#1]
## 概要
マイクロサービスアーキテクチャで動作するAI Knowledge Assistantの基盤となるDocker開発環境を構築します。

## 詳細説明
ローカル開発環境として、すべてのマイクロサービスをDockerコンテナ上で動作させるための基盤を整備します。開発者が簡単に環境を立ち上げ、開発を開始できるようにします。

## 受け入れ条件
- [ ] docker-compose.ymlファイルが作成され、1コマンドで全サービスが起動する
- [ ] 各マイクロサービス用のDockerfileが適切に設定されている
- [ ] ホットリロード機能が有効になっている
- [ ] 環境変数の管理が.envファイルで行える
- [ ] READMEに環境構築手順が記載されている

## 技術的詳細
```yaml
# docker-compose.yml の基本構造
version: '3.8'
services:
  gateway:
    build: ./services/gateway-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    volumes:
      - ./services/gateway-service:/app
      - /app/node_modules
    depends_on:
      - auth
      - source
      
  auth:
    build: ./services/auth-service
    # ... 省略
```

## 依存関係
- なし（最初のタスク）

## 推定工数
- 8時間

## 関連情報
- Docker公式ドキュメント: https://docs.docker.com/
- docker-compose リファレンス: https://docs.docker.com/compose/

## チェックリスト
- [ ] プロジェクトルートディレクトリ構造の決定
- [ ] docker-compose.yml の作成
- [ ] 各サービス用Dockerfileのテンプレート作成
- [ ] .env.example ファイルの作成
- [ ] Makefile の作成（開発用コマンドのショートカット）
- [ ] .dockerignore ファイルの設定
