### ISSUE TITLE
[Phase 1] CI/CDパイプライン構築

### ISSUE THREAD

**Issue by umaidashi** [umaidashi/open-notebooklm#4]
## 概要
GitHub ActionsまたはGitLab CI/CDを使用して、自動ビルド、テスト、デプロイのパイプラインを構築します。

## 詳細説明
コードの品質を保証し、開発効率を向上させるため、継続的インテグレーション・継続的デリバリーのパイプラインを整備します。

## 受け入れ条件
- [ ] プルリクエスト時に自動テストが実行される
- [ ] TypeScriptのビルドエラーが検出される
- [ ] コードカバレッジレポートが生成される
- [ ] Dockerイメージの自動ビルドが設定されている
- [ ] ステージング環境への自動デプロイが可能

## 技術的詳細
```yaml
# .github/workflows/ci.yml
name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run linter
      run: npm run lint
    
    - name: Run tests
      run: npm run test:ci
    
    - name: Build
      run: npm run build
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
```

## 依存関係
- #2 TypeScript + Node.jsプロジェクト初期化

## 推定工数
- 6時間

## 関連情報
- GitHub Actions: https://docs.github.com/en/actions
- Docker Hub: https://hub.docker.com/

## チェックリスト
- [ ] CI設定ファイルの作成
- [ ] テストスクリプトの整備
- [ ] Dockerイメージビルドワークフロー
- [ ] 環境別デプロイ設定
- [ ] シークレット管理の設定
- [ ] ブランチ保護ルールの設定
